// prototype/src/pages/AdminPage.tsx
import { Link } from 'react-router-dom';

const sections = [
  { title: 'Пользователи', path: '/admin/users', description: 'CRUD пользователей, привязка к ролям и командам', icon: '👥' },
  { title: 'Роли и полномочия', path: '/admin/roles', description: 'Матрица permissions: консоль, события, источники, правила', icon: '🔐' },
  { title: 'Реестр КЕ', path: '/admin/ci', description: 'Конфигурационные элементы, теги, связь с продуктами', icon: '🖥' },
  { title: 'Карты событий', path: '/admin/search-folders', description: 'Преднастроенные фильтры консоли', icon: '🗂' },
  { title: 'Консоли доступа', path: '/admin/consoles', description: 'Разграничение консолей по тенанту/группе', icon: '📺', postMvp: true },
];

export function AdminPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-white">Администрирование</h1>
        <p className="text-sm text-gray-500 mt-1">Управление пользователями, ролями и справочниками</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {sections.map((s) => (
          s.postMvp ? (
            <div key={s.path} className="bg-[#252830] border border-[#3a3f4b] rounded-lg p-5 opacity-60">
              <div className="text-2xl mb-2">{s.icon}</div>
              <h2 className="text-sm font-medium text-white">{s.title}</h2>
              <p className="text-xs text-gray-500 mt-1">{s.description}</p>
              <span className="inline-block mt-2 text-[10px] text-amber-500">post-MVP</span>
            </div>
          ) : (
            <Link key={s.path} to={s.path} className="bg-[#252830] border border-[#3a3f4b] rounded-lg p-5 hover:border-[#4a9eff]/50 transition-colors">
              <div className="text-2xl mb-2">{s.icon}</div>
              <h2 className="text-sm font-medium text-white">{s.title}</h2>
              <p className="text-xs text-gray-500 mt-1">{s.description}</p>
            </Link>
          )
        ))}
      </div>
    </div>
  );
}

// frontend/src/app/pages/admin/admin-page.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { PageHeaderComponent } from '../../shared/page-header/page-header.component';

@Component({
  selector: 'app-admin',
  standalone: true,
  imports: [RouterLink, PageHeaderComponent],
  template: `
    <app-page-header title="Администрирование" subtitle="Управление пользователями, ролями и конфигурацией" />
    <div class="hub-grid">
      @for (item of items; track item.path) {
        <a [routerLink]="item.path" class="hub-card">
          <span class="icon">{{ item.icon }}</span>
          <span class="title">{{ item.title }}</span>
          <span class="desc">{{ item.desc }}</span>
        </a>
      }
    </div>
  `,
  styles: [
    `
      .hub-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 1rem; }
      .hub-card { display: flex; flex-direction: column; gap: 0.5rem; padding: 1.25rem; background: var(--bg-sidebar); border: 1px solid var(--border); border-radius: 8px; text-decoration: none; transition: border-color 0.15s; }
      .hub-card:hover { border-color: var(--accent); }
      .icon { font-size: 1.5rem; }
      .title { color: var(--text-primary); font-weight: 500; font-size: 0.9375rem; }
      .desc { color: var(--text-muted); font-size: 0.75rem; }
    `,
  ],
})
export class AdminPageComponent {
  readonly items = [
    { path: '/admin/users', icon: '👤', title: 'Пользователи', desc: 'CRUD, роли, команды' },
    { path: '/admin/roles', icon: '🔐', title: 'Роли и полномочия', desc: 'Матрица permissions' },
    { path: '/admin/ci', icon: '🖥', title: 'Реестр КЕ', desc: 'Конфигурационные элементы' },
    { path: '/admin/search-folders', icon: '🗂', title: 'Карты событий', desc: 'Сохранённые фильтры консоли' },
  ];
}
