// frontend/src/app/shared/severity-badge/severity-badge.component.ts
import { Component, Input } from '@angular/core';
import { Severity } from '../../core/api/api.models';

const SEVERITY_COLORS: Record<Severity, string> = {
  fatal: '#dc2626',
  critical: '#dc2626',
  major: '#ea580c',
  minor: '#ca8a04',
  warning: '#eab308',
  normal: '#3b82f6',
};

const SEVERITY_LABELS: Record<Severity, string> = {
  fatal: 'Авария',
  critical: 'Критично',
  major: 'Существенно',
  minor: 'Незначительно',
  warning: 'Предупреждение',
  normal: 'Норма',
};

@Component({
  selector: 'app-severity-badge',
  standalone: true,
  template: `
    @if (compact) {
      <span class="compact">
        <span class="dot" [style.background-color]="color"></span>
        <span class="label">{{ SEVERITY_LABELS[severity] }}</span>
      </span>
    } @else {
      <span class="badge" [style.background-color]="color">{{ SEVERITY_LABELS[severity] }}</span>
    }
  `,
  styles: [
    `
      .compact { display: inline-flex; align-items: center; gap: 0.375rem; }
      .dot { width: 8px; height: 8px; border-radius: 50%; }
      .label { font-size: 0.75rem; color: #d1d5db; }
      .badge {
        display: inline-block;
        padding: 2px 8px;
        border-radius: 4px;
        font-size: 11px;
        font-weight: 600;
        text-transform: uppercase;
        color: #fff;
      }
    `,
  ],
})
export class SeverityBadgeComponent {
  readonly SEVERITY_LABELS = SEVERITY_LABELS;
  @Input({ required: true }) severity!: Severity;
  @Input() compact = false;

  get color(): string {
    return SEVERITY_COLORS[this.severity] ?? '#9e9e9e';
  }
}

// prototype/src/components/SeverityBadge.tsx
import type { Severity } from '../data/mock';
import { severityLabels } from '../data/mock';

const severityColors: Record<Severity, string> = {
  fatal: 'bg-[#dc2626] text-white',
  critical: 'bg-[#dc2626] text-white',
  major: 'bg-[#ea580c] text-white',
  minor: 'bg-[#ca8a04] text-white',
  warning: 'bg-[#eab308] text-[#1a1d23]',
  normal: 'bg-[#3b82f6] text-white',
};

const severityDots: Record<Severity, string> = {
  fatal: 'bg-[#dc2626]',
  critical: 'bg-[#dc2626]',
  major: 'bg-[#ea580c]',
  minor: 'bg-[#ca8a04]',
  warning: 'bg-[#eab308]',
  normal: 'bg-[#3b82f6]',
};

interface Props {
  severity: Severity;
  compact?: boolean;
}

export function SeverityBadge({ severity, compact }: Props) {
  if (compact) {
    return (
      <span className="inline-flex items-center gap-1.5">
        <span className={`w-2 h-2 rounded-full ${severityDots[severity]}`} />
        <span className="text-xs">{severityLabels[severity]}</span>
      </span>
    );
  }
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${severityColors[severity]}`}>
      {severityLabels[severity]}
    </span>
  );
}
