// frontend/src/app/shared/health/ci-health-tab.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ConfigurationItem, Severity } from '../../core/api/api.models';
import { CiHealthProfile } from '../../core/health/health.models';
import { HealthBadgeComponent } from './health-badge.component';
import { HealthTimelineChartComponent } from './health-timeline-chart.component';
import { SeverityBadgeComponent } from '../severity-badge/severity-badge.component';

@Component({
  selector: 'app-ci-health-tab',
  standalone: true,
  imports: [RouterLink, HealthBadgeComponent, HealthTimelineChartComponent, SeverityBadgeComponent],
  template: `
    <div class="root">
      <div class="summary card">
        <div class="summary-main">
          <div class="percent-box" [attr.data-level]="health.currentHealth">
            {{ health.healthPercent }}%
          </div>
          <div>
            <div class="label">Текущее здоровье КЕ</div>
            <app-health-badge [level]="health.currentHealth" [percent]="health.healthPercent" />
            <div class="fqdn">{{ ci.fqdn }}</div>
            <div class="meta">{{ ci.system }} · {{ ci.ciType }}</div>
          </div>
        </div>
        <div class="summary-side">
          <div>
            <div class="label">Мин. за сутки</div>
            <app-health-badge [level]="health.minToday" [percent]="health.minTodayPercent" [compact]="true" />
          </div>
          <div>
            <div class="label">Макс. за сутки</div>
            <app-health-badge [level]="health.maxToday" [percent]="health.maxTodayPercent" [compact]="true" />
          </div>
          <button type="button" class="rca-btn" [class.open]="rcaOpen" (click)="rcaOpen = !rcaOpen">RCA</button>
        </div>
      </div>

      <div class="grid">
        <div class="card components">
          <h3>Здоровье компонентов</h3>
          <table>
            <thead>
              <tr><th>Компонент</th><th>Здоровье</th><th class="num">Ущерб от компонентов</th><th class="num">Ущерб от влияния</th></tr>
            </thead>
            <tbody>
              @for (c of health.components; track c.id) {
                <tr>
                  <td>{{ c.name }}</td>
                  <td><app-health-badge [level]="c.health" [percent]="c.healthPercent" [compact]="true" /></td>
                  <td class="num">{{ c.damageFromComponents }}%</td>
                  <td class="num">{{ c.damageFromInfluence }}%</td>
                </tr>
              }
            </tbody>
          </table>
        </div>
        <div class="card signals">
          <div class="signals-head">
            <h3>Сигналы</h3>
            <span class="count">{{ totalSignals }}</span>
          </div>
          @for (s of severities; track s) {
            <div class="signal-row">
              <app-severity-badge [severity]="s" [compact]="true" />
              <span>{{ health.signalsBySeverity[s] }}</span>
            </div>
          }
          <a [routerLink]="['/console']" [queryParams]="{ ci: ci.id }" class="link">Перейти к сигналам →</a>
        </div>
      </div>

      @if (health.dependents.length) {
        <div class="card">
          <h3>Зависимые КЕ (влияние)</h3>
          @for (d of health.dependents; track d.id) {
            <div class="dependent">
              <span class="icon">{{ influenceIcon(d.influenceType) }}</span>
              <div class="dep-main">
                <div class="fqdn">{{ d.fqdn }}</div>
                @if (d.componentName) {
                  <div class="meta">Компонент: {{ d.componentName }}</div>
                }
              </div>
              <app-health-badge [level]="d.health" [percent]="d.healthPercent" [compact]="true" />
            </div>
          }
        </div>
      }

      <app-health-timeline-chart [timeline]="health.timeline" />

      @if (rcaOpen) {
        <div class="rca-panel">
          <div class="rca-head">
            <h3>Root Cause Analysis (RCA)</h3>
            <button type="button" class="close" (click)="rcaOpen = false">×</button>
          </div>
          <div class="rca-toolbar">
            <label>
              Порог ущерба (%)
              <input type="number" min="0" max="100" [value]="damageThreshold" (input)="onThreshold($event)" />
            </label>
          </div>
          <div class="rca-body">
            <table>
              <thead>
                <tr><th>Источник</th><th>Тип</th><th class="num">Ущерб</th><th>Здоровье</th></tr>
              </thead>
              <tbody>
                @if (rcaRows.length === 0) {
                  <tr><td colspan="4" class="empty">Нет источников с ущербом ≥ {{ damageThreshold }}%</td></tr>
                }
                @for (r of rcaRows; track r.name + r.type) {
                  <tr>
                    <td>{{ r.name }}</td>
                    <td>{{ r.type }}</td>
                    <td class="num damage">{{ r.damage }}%</td>
                    <td><app-health-badge [level]="r.health" [percent]="r.percent" [compact]="true" /></td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        </div>
      }
    </div>
  `,
  styles: [
    `
      .root { display: flex; flex-direction: column; gap: 1rem; }
      .card { background: #252830; border: 1px solid #3a3f4b; border-radius: 8px; padding: 1rem; }
      .summary { display: flex; justify-content: space-between; gap: 1rem; flex-wrap: wrap; }
      .summary-main { display: flex; gap: 1rem; align-items: flex-start; }
      .percent-box {
        width: 4rem; height: 4rem; border-radius: 8px; display: flex; align-items: center; justify-content: center;
        font-size: 1.5rem; font-weight: 700; border: 2px solid;
      }
      .percent-box[data-level='ok'] { border-color: #22c55e; background: rgba(34,197,94,0.12); color: #22c55e; }
      .percent-box[data-level='warning'] { border-color: #eab308; background: rgba(234,179,8,0.12); color: #eab308; }
      .percent-box[data-level='major'] { border-color: #ea580c; background: rgba(234,88,12,0.12); color: #ea580c; }
      .percent-box[data-level='fatal'], .percent-box[data-level='critical'] { border-color: #dc2626; background: rgba(220,38,38,0.12); color: #dc2626; }
      .label { font-size: 0.75rem; color: #6b7280; margin-bottom: 0.25rem; }
      .fqdn { font-family: var(--font-mono); font-size: 0.875rem; color: #d1d5db; margin-top: 0.5rem; }
      .meta { font-size: 0.75rem; color: #6b7280; }
      .summary-side { display: flex; gap: 1.5rem; align-items: flex-start; font-size: 0.875rem; }
      .rca-btn {
        padding: 0.375rem 0.75rem; font-size: 0.75rem; border-radius: 6px; cursor: pointer;
        background: #1a1d23; border: 1px solid #3a3f4b; color: #d1d5db;
      }
      .rca-btn.open { background: rgba(74,158,255,0.2); border-color: #4a9eff; color: #4a9eff; }
      .grid { display: grid; grid-template-columns: 2fr 1fr; gap: 1rem; }
      @media (max-width: 1200px) { .grid { grid-template-columns: 1fr; } }
      h3 { margin: 0 0 0.75rem; font-size: 0.875rem; color: #fff; font-weight: 500; }
      table { width: 100%; font-size: 0.875rem; border-collapse: collapse; }
      th, td { padding: 0.5rem 0; border-bottom: 1px solid rgba(58,63,75,0.5); text-align: left; }
      th { font-size: 0.75rem; color: #6b7280; font-weight: 400; }
      .num { text-align: right; color: #9ca3af; }
      .signals-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem; }
      .signals-head h3 { margin: 0; }
      .count { font-size: 1.125rem; font-weight: 700; color: #fff; }
      .signal-row { display: flex; justify-content: space-between; font-size: 0.875rem; margin-bottom: 0.5rem; }
      .link { display: block; margin-top: 1rem; text-align: center; font-size: 0.75rem; color: #4a9eff; text-decoration: none; }
      .dependent { display: flex; align-items: center; gap: 0.75rem; padding: 0.5rem 0.75rem; background: #1a1d23; border: 1px solid #3a3f4b; border-radius: 6px; margin-bottom: 0.5rem; }
      .icon { font-size: 1rem; }
      .dep-main { flex: 1; min-width: 0; }
      .rca-panel {
        position: fixed; inset: auto 0 0 0; z-index: 40; background: #1a1d23; border-top: 1px solid #3a3f4b;
        box-shadow: 0 -8px 24px rgba(0,0,0,0.4); max-height: 50vh; display: flex; flex-direction: column;
      }
      .rca-head { display: flex; justify-content: space-between; padding: 0.75rem 1rem; border-bottom: 1px solid #3a3f4b; }
      .rca-head h3 { margin: 0; font-size: 0.875rem; color: #fff; }
      .close { background: none; border: none; color: #6b7280; font-size: 1.25rem; cursor: pointer; }
      .rca-toolbar { padding: 0.75rem 1rem; border-bottom: 1px solid #3a3f4b; font-size: 0.75rem; color: #9ca3af; }
      .rca-toolbar input { margin-left: 0.5rem; width: 4rem; padding: 0.25rem 0.5rem; background: #252830; border: 1px solid #3a3f4b; border-radius: 4px; color: #fff; }
      .rca-body { flex: 1; overflow: auto; padding: 0.5rem 1rem; }
      .empty { text-align: center; color: #6b7280; padding: 1rem; }
      .damage { color: #dc2626; }
    `,
  ],
})
export class CiHealthTabComponent {
  @Input({ required: true }) ci!: ConfigurationItem;
  @Input({ required: true }) health!: CiHealthProfile;

  rcaOpen = false;
  damageThreshold = 30;
  readonly severities: Severity[] = ['fatal', 'critical', 'major', 'minor', 'warning', 'normal'];

  get totalSignals(): number {
    return Object.values(this.health.signalsBySeverity).reduce((a, b) => a + b, 0);
  }

  get rcaRows() {
    return [
      ...this.health.components.map((c) => ({
        name: c.name,
        type: 'Компонент',
        damage: c.damageFromComponents + c.damageFromInfluence,
        health: c.health,
        percent: c.healthPercent,
      })),
      ...this.health.dependents.map((d) => ({
        name: d.fqdn,
        type: 'Влияние',
        damage: 100 - d.healthPercent,
        health: d.health,
        percent: d.healthPercent,
      })),
    ]
      .filter((r) => r.damage >= this.damageThreshold)
      .sort((a, b) => b.damage - a.damage);
  }

  influenceIcon(type: string): string {
    if (type === 'combo') return '⊕';
    if (type === 'weighted') return '⚖';
    return '⚠';
  }

  onThreshold(event: Event): void {
    this.damageThreshold = Number((event.target as HTMLInputElement).value);
  }
}

// prototype/src/components/health/CiHealthTab.tsx
import { useState } from 'react';
import { Link } from 'react-router-dom';
import type { CiHealthProfile, ConfigurationItem, InfluenceType, Severity } from '../../data/mock';
import { HealthBadge } from './HealthBadge';
import { HealthTimelineChart } from './HealthTimelineChart';
import { SeverityBadge } from '../SeverityBadge';

const influenceLabels: Record<InfluenceType, string> = {
  combo: 'Комбинированное',
  weighted: 'Взвешенное',
  critical: 'Критическое',
};

const influenceIcons: Record<InfluenceType, string> = {
  combo: '⊕',
  weighted: '⚖',
  critical: '⚠',
};

interface Props {
  ci: ConfigurationItem;
  health: CiHealthProfile;
}

export function CiHealthTab({ ci, health }: Props) {
  const [rcaOpen, setRcaOpen] = useState(false);
  const [damageThreshold, setDamageThreshold] = useState(30);
  const totalSignals = Object.values(health.signalsBySeverity).reduce((a, b) => a + b, 0);

  const rcaRows = [
    ...health.components.map((c) => ({
      name: c.name,
      type: 'Компонент',
      damage: c.damageFromComponents + c.damageFromInfluence,
      health: c.health,
      percent: c.healthPercent,
    })),
    ...health.dependents.map((d) => ({
      name: d.fqdn,
      type: 'Влияние',
      damage: 100 - d.healthPercent,
      health: d.health,
      percent: d.healthPercent,
    })),
  ].filter((r) => r.damage >= damageThreshold).sort((a, b) => b.damage - a.damage);

  return (
    <div className="space-y-4">
      {/* Текущее здоровье КЕ */}
      <div className="bg-[#252830] border border-[#3a3f4b] rounded-lg p-4">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-center gap-4">
            <div
              className="w-16 h-16 rounded-lg flex items-center justify-center text-2xl font-bold border-2"
              style={{
                borderColor: health.currentHealth === 'ok' ? '#22c55e'
                  : health.currentHealth === 'warning' ? '#eab308'
                  : health.currentHealth === 'major' ? '#ea580c'
                  : '#dc2626',
                backgroundColor: `${health.currentHealth === 'ok' ? '#22c55e' : health.currentHealth === 'warning' ? '#eab308' : health.currentHealth === 'major' ? '#ea580c' : '#dc2626'}20`,
                color: health.currentHealth === 'ok' ? '#22c55e' : health.currentHealth === 'warning' ? '#eab308' : health.currentHealth === 'major' ? '#ea580c' : '#dc2626',
              }}
            >
              {health.healthPercent}%
            </div>
            <div>
              <div className="text-xs text-gray-500 mb-1">Текущее здоровье КЕ</div>
              <HealthBadge level={health.currentHealth} percent={health.healthPercent} />
              <div className="font-mono text-sm text-gray-300 mt-2">{ci.fqdn}</div>
              <div className="text-xs text-gray-500">{ci.system} · {ci.ciType}</div>
            </div>
          </div>
          <div className="flex gap-6 text-sm">
            <div>
              <div className="text-xs text-gray-500 mb-1">Мин. за сутки</div>
              <HealthBadge level={health.minToday} compact percent={health.minTodayPercent} />
            </div>
            <div>
              <div className="text-xs text-gray-500 mb-1">Макс. за сутки</div>
              <HealthBadge level={health.maxToday} compact percent={health.maxTodayPercent} />
            </div>
            <button
              type="button"
              onClick={() => setRcaOpen(!rcaOpen)}
              className={`px-3 py-1.5 text-xs rounded border transition-colors ${
                rcaOpen
                  ? 'bg-[#4a9eff]/20 border-[#4a9eff] text-[#4a9eff]'
                  : 'bg-[#1a1d23] border-[#3a3f4b] text-gray-300 hover:border-[#4a9eff]/50'
              }`}
            >
              RCA
            </button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
        {/* Компоненты */}
        <div className="xl:col-span-2 bg-[#252830] border border-[#3a3f4b] rounded-lg p-4">
          <h3 className="text-sm font-medium text-white mb-3">Здоровье компонентов</h3>
          <table className="w-full text-sm">
            <thead>
              <tr className="text-xs text-gray-500 border-b border-[#3a3f4b]">
                <th className="text-left py-2 font-normal">Компонент</th>
                <th className="text-left py-2 font-normal">Здоровье</th>
                <th className="text-right py-2 font-normal">Ущерб от компонентов</th>
                <th className="text-right py-2 font-normal">Ущерб от влияния</th>
              </tr>
            </thead>
            <tbody>
              {health.components.map((c) => (
                <tr key={c.id} className="border-b border-[#3a3f4b]/50 hover:bg-[#3a3f4b]/20">
                  <td className="py-2.5 text-gray-300">{c.name}</td>
                  <td className="py-2.5">
                    <HealthBadge level={c.health} compact percent={c.healthPercent} />
                  </td>
                  <td className="py-2.5 text-right text-gray-400">{c.damageFromComponents}%</td>
                  <td className="py-2.5 text-right text-gray-400">{c.damageFromInfluence}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Сигналы */}
        <div className="bg-[#252830] border border-[#3a3f4b] rounded-lg p-4">
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-sm font-medium text-white">Сигналы</h3>
            <span className="text-lg font-bold text-white">{totalSignals}</span>
          </div>
          <div className="space-y-2">
            {(['fatal', 'critical', 'major', 'minor', 'warning', 'normal'] as Severity[]).map((s) => (
              <div key={s} className="flex items-center justify-between text-sm">
                <SeverityBadge severity={s} compact />
                <span className="text-gray-400">{health.signalsBySeverity[s]}</span>
              </div>
            ))}
          </div>
          <Link
            to={`/console?ci=${ci.id}`}
            className="mt-4 block text-center text-xs text-[#4a9eff] hover:underline"
          >
            Перейти к сигналам →
          </Link>
        </div>
      </div>

      {/* Зависимые КЕ */}
      {health.dependents.length > 0 && (
        <div className="bg-[#252830] border border-[#3a3f4b] rounded-lg p-4">
          <h3 className="text-sm font-medium text-white mb-3">Зависимые КЕ (влияние)</h3>
          <div className="space-y-2">
            {health.dependents.map((d) => (
              <div
                key={d.id}
                className="flex items-center gap-3 px-3 py-2 bg-[#1a1d23] rounded border border-[#3a3f4b] text-sm"
              >
                <span className="text-base" title={influenceLabels[d.influenceType]}>
                  {influenceIcons[d.influenceType]}
                </span>
                <div className="flex-1 min-w-0">
                  <div className="font-mono text-gray-300 truncate">{d.fqdn}</div>
                  {d.componentName && (
                    <div className="text-xs text-gray-500">Компонент: {d.componentName}</div>
                  )}
                </div>
                <span className="text-xs text-gray-500">{influenceLabels[d.influenceType]}</span>
                <HealthBadge level={d.health} compact percent={d.healthPercent} />
              </div>
            ))}
          </div>
        </div>
      )}

      <HealthTimelineChart timeline={health.timeline} />

      {/* RCA панель снизу */}
      {rcaOpen && (
        <div className="fixed inset-x-0 bottom-0 z-40 bg-[#1a1d23] border-t border-[#3a3f4b] shadow-2xl max-h-[50vh] flex flex-col">
          <div className="flex items-center justify-between px-4 py-3 border-b border-[#3a3f4b]">
            <h3 className="text-sm font-medium text-white">Root Cause Analysis (RCA)</h3>
            <button
              type="button"
              onClick={() => setRcaOpen(false)}
              className="text-gray-500 hover:text-white text-lg leading-none"
            >
              ×
            </button>
          </div>
          <div className="px-4 py-3 flex items-center gap-4 border-b border-[#3a3f4b]">
            <label className="text-xs text-gray-400">
              Порог ущерба (%)
              <input
                type="number"
                min={0}
                max={100}
                value={damageThreshold}
                onChange={(e) => setDamageThreshold(Number(e.target.value))}
                className="ml-2 w-16 px-2 py-1 bg-[#252830] border border-[#3a3f4b] rounded text-white text-xs"
              />
            </label>
            <button
              type="button"
              className="px-3 py-1 text-xs bg-[#4a9eff] text-white rounded hover:bg-[#3a8eef]"
            >
              Пересчитать
            </button>
          </div>
          <div className="flex-1 overflow-auto px-4 py-2">
            <table className="w-full text-sm">
              <thead className="sticky top-0 bg-[#1a1d23]">
                <tr className="text-xs text-gray-500 border-b border-[#3a3f4b]">
                  <th className="text-left py-2 font-normal">Источник</th>
                  <th className="text-left py-2 font-normal">Тип</th>
                  <th className="text-right py-2 font-normal">Ущерб</th>
                  <th className="text-left py-2 font-normal pl-4">Здоровье</th>
                </tr>
              </thead>
              <tbody>
                {rcaRows.length === 0 ? (
                  <tr>
                    <td colSpan={4} className="py-4 text-center text-gray-500 text-sm">
                      Нет источников с ущербом ≥ {damageThreshold}%
                    </td>
                  </tr>
                ) : (
                  rcaRows.map((r, i) => (
                    <tr key={i} className="border-b border-[#3a3f4b]/50">
                      <td className="py-2 text-gray-300">{r.name}</td>
                      <td className="py-2 text-gray-500">{r.type}</td>
                      <td className="py-2 text-right text-[#dc2626]">{r.damage}%</td>
                      <td className="py-2 pl-4">
                        <HealthBadge level={r.health} compact percent={r.percent} />
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
