// frontend/src/app/shared/health/health-timeline-chart.component.ts
import { Component, Input } from '@angular/core';
import { HealthTimelinePoint } from '../../core/health/health.models';
import { HealthBadgeComponent } from './health-badge.component';

@Component({
  selector: 'app-health-timeline-chart',
  standalone: true,
  imports: [HealthBadgeComponent],
  template: `
    <div class="panel">
      <div class="head">
        <h3>График здоровья за сутки</h3>
        <span class="hint">мин. {{ minPercent }}%</span>
      </div>
      <div class="chart">
        @for (point of timeline; track $index) {
          <div class="bar-col" [title]="point.time + ': ' + point.percent + '%'">
            <div class="bar" [style.height.%]="point.percent" [style.background-color]="barColor(point.level)"></div>
            @if ($index % 2 === 0) {
              <span class="time">{{ point.time }}</span>
            }
          </div>
        }
      </div>
      <div class="footer">
        <span class="hint">Текущее:</span>
        @if (timeline.length) {
          <app-health-badge
            [level]="timeline[timeline.length - 1].level"
            [percent]="timeline[timeline.length - 1].percent"
            [compact]="true"
          />
        }
      </div>
    </div>
  `,
  styles: [
    `
      .panel { background: #252830; border: 1px solid #3a3f4b; border-radius: 8px; padding: 1rem; }
      .head { display: flex; justify-content: space-between; margin-bottom: 0.75rem; }
      h3 { margin: 0; font-size: 0.875rem; color: #fff; font-weight: 500; }
      .hint { font-size: 0.75rem; color: #6b7280; }
      .chart { display: flex; align-items: flex-end; gap: 0.25rem; height: 8rem; }
      .bar-col { flex: 1; display: flex; flex-direction: column; align-items: center; gap: 0.25rem; min-width: 0; }
      .bar { width: 100%; border-radius: 4px 4px 0 0; min-height: 4px; }
      .time { font-size: 9px; color: #6b7280; text-align: center; width: 100%; overflow: hidden; text-overflow: ellipsis; }
      .footer { display: flex; align-items: center; gap: 0.75rem; margin-top: 0.75rem; padding-top: 0.75rem; border-top: 1px solid #3a3f4b; }
    `,
  ],
})
export class HealthTimelineChartComponent {
  @Input({ required: true }) timeline!: HealthTimelinePoint[];

  get minPercent(): number {
    return this.timeline.length ? Math.min(...this.timeline.map((p) => p.percent)) : 0;
  }

  barColor(level: HealthTimelinePoint['level']): string {
    if (level === 'fatal' || level === 'critical') return '#dc2626';
    if (level === 'major') return '#ea580c';
    if (level === 'warning') return '#eab308';
    if (level === 'ok') return '#22c55e';
    return '#6b7280';
  }
}

// prototype/src/components/health/HealthTimelineChart.tsx
import type { CiHealthProfile } from '../../data/mock';
import { HealthBadge } from './HealthBadge';

interface Props {
  timeline: CiHealthProfile['timeline'];
}

export function HealthTimelineChart({ timeline }: Props) {
  const max = 100;
  const min = Math.min(...timeline.map((p) => p.percent));

  return (
    <div className="bg-[#252830] border border-[#3a3f4b] rounded-lg p-4">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-medium text-white">График здоровья за сутки</h3>
        <span className="text-xs text-gray-500">мин. {min}%</span>
      </div>
      <div className="relative h-32 flex items-end gap-1">
        {timeline.map((point, i) => {
          const height = (point.percent / max) * 100;
          const barColor =
            point.level === 'fatal' || point.level === 'critical' ? '#dc2626'
            : point.level === 'major' ? '#ea580c'
            : point.level === 'warning' ? '#eab308'
            : point.level === 'ok' ? '#22c55e'
            : '#6b7280';
          return (
            <div key={i} className="flex-1 flex flex-col items-center gap-1 min-w-0 group">
              <div
                className="w-full rounded-t transition-opacity group-hover:opacity-80 cursor-pointer"
                style={{ height: `${height}%`, backgroundColor: barColor, minHeight: 4 }}
                title={`${point.time}: ${point.percent}%`}
              />
              {i % 2 === 0 && (
                <span className="text-[9px] text-gray-600 truncate w-full text-center">{point.time}</span>
              )}
            </div>
          );
        })}
      </div>
      <div className="flex items-center gap-3 mt-3 pt-3 border-t border-[#3a3f4b]">
        <span className="text-xs text-gray-500">Текущее:</span>
        {timeline.length > 0 && (
          <HealthBadge level={timeline[timeline.length - 1].level} compact percent={timeline[timeline.length - 1].percent} />
        )}
      </div>
    </div>
  );
}
