// frontend/src/app/shared/health/operative-center-panel.component.ts
import { SlicePipe } from '@angular/common';
import { Component, Input, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ConfigurationItem, Event, ProductHealth } from '../../core/api/api.models';
import { CiHealthProfile } from '../../core/health/health.models';
import { CiHealthTabComponent } from './ci-health-tab.component';
import { HealthBadgeComponent } from './health-badge.component';
import { SeverityBadgeComponent } from '../severity-badge/severity-badge.component';
import { StatusBadgeComponent } from '../status-badge/status-badge.component';

type Tab = 'signals' | 'health' | 'params' | 'events';

@Component({
  selector: 'app-operative-center-panel',
  standalone: true,
  imports: [
    SlicePipe,
    RouterLink,
    CiHealthTabComponent,
    HealthBadgeComponent,
    SeverityBadgeComponent,
    StatusBadgeComponent,
  ],
  template: `
    @if (selectedCi && health) {
      <div class="panel">
        <div class="header">
          <div>
            <div class="subtitle">Оперативный центр · {{ product.name }}</div>
            <h2 class="fqdn">{{ selectedCi.fqdn }}</h2>
            <div class="meta">{{ selectedCi.system }} · {{ selectedCi.ciType }}</div>
          </div>
          <app-health-badge [level]="health.currentHealth" [percent]="health.healthPercent" />
        </div>

        <div class="tabs">
          @for (tab of tabs; track tab.id) {
            <button type="button" class="tab" [class.active]="activeTab === tab.id" (click)="activeTab = tab.id">
              {{ tab.label }}
              @if (tab.id === 'signals' && totalSignals > 0) {
                <span class="badge-count">{{ totalSignals }}</span>
              }
            </button>
          }
        </div>

        <div class="content">
          @if (activeTab === 'health') {
            <app-ci-health-tab [ci]="selectedCi" [health]="health" />
          }
          @if (activeTab === 'signals') {
            <div class="card">
              <p class="muted">Активные сигналы по КЕ — {{ totalSignals }} шт.</p>
              <div class="signal-list">
                @for (e of ciActiveEvents; track e.id) {
                  <a [routerLink]="['/console', e.id]" class="signal-row">
                    <app-severity-badge [severity]="e.severity" [compact]="true" />
                    <span class="title">{{ e.title }}</span>
                    <app-status-badge [status]="e.status" />
                  </a>
                }
                @if (ciActiveEvents.length === 0) {
                  <p class="muted">Нет активных сигналов</p>
                }
              </div>
              <a [routerLink]="['/console']" [queryParams]="{ ci: selectedCi.id }" class="link">Открыть в консоли →</a>
            </div>
          }
          @if (activeTab === 'params') {
            <div class="card">
              <h3>Параметры КЕ</h3>
              <dl class="params">
                <div><dt>FQDN</dt><dd>{{ selectedCi.fqdn }}</dd></div>
                <div><dt>Тип</dt><dd>{{ selectedCi.ciType }}</dd></div>
                <div><dt>Система</dt><dd>{{ selectedCi.system }}</dd></div>
                <div><dt>Подсистема</dt><dd>{{ selectedCi.subsystem }}</dd></div>
                <div><dt>ПО</dt><dd>{{ selectedCi.software }}</dd></div>
                <div><dt>Тенант</dt><dd>{{ product.tenant }}</dd></div>
                <div><dt>Площадка</dt><dd>{{ product.site }}</dd></div>
              </dl>
              <div class="tags">
                @for (tag of allTags; track tag) {
                  <span class="tag">{{ tag }}</span>
                }
              </div>
            </div>
          }
          @if (activeTab === 'events') {
            <div class="card">
              <div class="card-head">
                <h3>События КЕ</h3>
                <a [routerLink]="['/console']" [queryParams]="{ ci: selectedCi.id }" class="link">Консоль →</a>
              </div>
              <div class="signal-list">
                @for (e of ciAllEvents; track e.id) {
                  <a [routerLink]="['/console', e.id]" class="event-row">
                    <app-status-badge [status]="e.status" />
                    <app-severity-badge [severity]="e.severity" [compact]="true" />
                    <span class="title">{{ e.title }}</span>
                    <span class="time">{{ e.createdAt | slice: 0 : 16 }}</span>
                  </a>
                }
              </div>
            </div>
          }
        </div>
      </div>
    } @else {
      <p class="muted">Выберите КЕ</p>
    }
  `,
  styles: [
    `
      .panel { display: flex; flex-direction: column; height: 100%; min-height: 0; }
      .header { display: flex; justify-content: space-between; margin-bottom: 1rem; }
      .subtitle { font-size: 0.75rem; color: #6b7280; }
      .fqdn { margin: 0.125rem 0 0; font-size: 1.125rem; font-weight: 600; color: #fff; font-family: var(--font-mono); }
      .meta { font-size: 0.75rem; color: #6b7280; margin-top: 0.125rem; }
      .tabs { display: flex; border-bottom: 1px solid #3a3f4b; margin-bottom: 1rem; }
      .tab {
        padding: 0.5rem 1rem; font-size: 0.875rem; background: none; border: none; border-bottom: 2px solid transparent;
        margin-bottom: -1px; color: #6b7280; cursor: pointer;
      }
      .tab:hover { color: #d1d5db; }
      .tab.active { border-bottom-color: #4a9eff; color: #4a9eff; }
      .badge-count { margin-left: 0.375rem; padding: 0 0.375rem; font-size: 10px; border-radius: 4px; background: #dc2626; color: #fff; }
      .content { flex: 1; overflow: auto; min-height: 0; }
      .card { background: #252830; border: 1px solid #3a3f4b; border-radius: 8px; padding: 1rem; }
      .card h3 { margin: 0 0 0.75rem; font-size: 0.875rem; color: #fff; font-weight: 500; }
      .card-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem; }
      .card-head h3 { margin: 0; }
      .muted { font-size: 0.875rem; color: #6b7280; }
      .signal-list { display: flex; flex-direction: column; gap: 0.5rem; margin: 1rem 0; }
      .signal-row, .event-row {
        display: flex; align-items: center; gap: 0.5rem; padding: 0.5rem 0.75rem; border-radius: 6px;
        border: 1px solid #3a3f4b; text-decoration: none; font-size: 0.875rem;
      }
      .signal-row:hover, .event-row:hover { background: rgba(58, 63, 75, 0.3); }
      .title { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: #d1d5db; }
      .time { font-size: 0.75rem; color: #6b7280; }
      .link { font-size: 0.75rem; color: #4a9eff; text-decoration: none; }
      .link:hover { text-decoration: underline; }
      .params { display: grid; grid-template-columns: 1fr 1fr; gap: 0.75rem; font-size: 0.875rem; }
      .params dt { font-size: 0.75rem; color: #6b7280; }
      .params dd { margin: 0.125rem 0 0; color: #d1d5db; }
      .tags { display: flex; flex-wrap: wrap; gap: 0.25rem; margin-top: 1rem; }
      .tag { padding: 0.125rem 0.5rem; font-size: 0.75rem; border-radius: 4px; background: rgba(58, 63, 75, 0.5); color: #9ca3af; }
    `,
  ],
})
export class OperativeCenterPanelComponent implements OnInit {
  @Input({ required: true }) product!: ProductHealth;
  @Input({ required: true }) ciList!: ConfigurationItem[];
  @Input({ required: true }) selectedCiId!: string;
  @Input({ required: true }) profiles!: Record<string, CiHealthProfile>;
  @Input({ required: true }) events!: Event[];
  @Input() defaultTab: Tab = 'health';

  activeTab: Tab = 'health';

  ngOnInit(): void {
    this.activeTab = this.defaultTab;
  }

  readonly tabs: { id: Tab; label: string }[] = [
    { id: 'signals', label: 'Сигналы' },
    { id: 'health', label: 'Здоровье' },
    { id: 'params', label: 'Параметры' },
    { id: 'events', label: 'События' },
  ];

  get selectedCi(): ConfigurationItem | undefined {
    return this.ciList.find((c) => c.id === this.selectedCiId) ?? this.ciList[0];
  }

  get health(): CiHealthProfile | undefined {
    const ci = this.selectedCi;
    return ci ? this.profiles[ci.id] : undefined;
  }

  get ciActiveEvents(): Event[] {
    const ci = this.selectedCi;
    if (!ci) return [];
    return this.events.filter((e) => e.ciId === ci.id && e.status !== 'closed' && e.status !== 'archived');
  }

  get ciAllEvents(): Event[] {
    const ci = this.selectedCi;
    if (!ci) return [];
    return this.events.filter((e) => e.ciId === ci.id).slice(0, 10);
  }

  get totalSignals(): number {
    return this.health ? Object.values(this.health.signalsBySeverity).reduce((a, b) => a + b, 0) : 0;
  }

  get allTags(): string[] {
    const ci = this.selectedCi;
    if (!ci) return this.product.tags;
    return [...new Set([...(ci.tags ?? []), ...(this.product.tags ?? [])])];
  }
}

// prototype/src/components/health/OperativeCenterPanel.tsx
import { useState } from 'react';
import { Link } from 'react-router-dom';
import type { ConfigurationItem, ProductHealth } from '../../data/mock';
import { events, getCiHealth } from '../../data/mock';
import { CiHealthTab } from './CiHealthTab';
import { HealthBadge } from './HealthBadge';
import { SeverityBadge } from '../SeverityBadge';
import { StatusBadge } from '../StatusBadge';

type Tab = 'signals' | 'health' | 'params' | 'events';

interface Props {
  product: ProductHealth;
  ciList: ConfigurationItem[];
  selectedCiId: string;
  onSelectCi: (ciId: string) => void;
  defaultTab?: Tab;
}

const tabs: { id: Tab; label: string }[] = [
  { id: 'signals', label: 'Сигналы' },
  { id: 'health', label: 'Здоровье' },
  { id: 'params', label: 'Параметры' },
  { id: 'events', label: 'События' },
];

export function OperativeCenterPanel({ product, ciList, selectedCiId, onSelectCi, defaultTab = 'health' }: Props) {
  const [activeTab, setActiveTab] = useState<Tab>(defaultTab);
  const selectedCi = ciList.find((c) => c.id === selectedCiId) ?? ciList[0];
  const health = selectedCi ? getCiHealth(selectedCi.id) : null;
  const ciEvents = events.filter(
    (e) => e.ciId === selectedCi?.id && e.status !== 'closed' && e.status !== 'archived'
  );
  const totalSignals = health
    ? Object.values(health.signalsBySeverity).reduce((a, b) => a + b, 0)
    : 0;

  if (!selectedCi || !health) {
    return <p className="text-gray-500 text-sm">Выберите КЕ</p>;
  }

  return (
    <div className="flex flex-col h-full min-h-0">
      {/* Заголовок оперативного центра */}
      <div className="flex items-start justify-between mb-4">
        <div>
          <div className="text-xs text-gray-500">Оперативный центр · {product.name}</div>
          <h2 className="text-lg font-semibold text-white mt-0.5 font-mono">{selectedCi.fqdn}</h2>
          <div className="text-xs text-gray-500 mt-0.5">{selectedCi.system} · {selectedCi.ciType}</div>
        </div>
        <HealthBadge level={health.currentHealth} percent={health.healthPercent} />
      </div>

      {/* Вкладки */}
      <div className="flex border-b border-[#3a3f4b] mb-4">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            type="button"
            onClick={() => setActiveTab(tab.id)}
            className={`px-4 py-2 text-sm border-b-2 -mb-px transition-colors ${
              activeTab === tab.id
                ? 'border-[#4a9eff] text-[#4a9eff]'
                : 'border-transparent text-gray-500 hover:text-gray-300'
            }`}
          >
            {tab.label}
            {tab.id === 'signals' && totalSignals > 0 && (
              <span className="ml-1.5 px-1.5 py-0.5 text-[10px] rounded bg-[#dc2626] text-white">
                {totalSignals}
              </span>
            )}
          </button>
        ))}
      </div>

      {/* Контент вкладок */}
      <div className="flex-1 overflow-auto min-h-0">
        {activeTab === 'health' && <CiHealthTab ci={selectedCi} health={health} />}
        {activeTab === 'signals' && (
          <div className="bg-[#252830] border border-[#3a3f4b] rounded-lg p-4">
            <p className="text-sm text-gray-400 mb-4">
              Активные сигналы по КЕ — {totalSignals} шт.
            </p>
            <div className="space-y-2 mb-4">
              {ciEvents.map((e) => (
                <Link
                  key={e.id}
                  to={`/console/${e.id}`}
                  className="flex items-center gap-2 px-3 py-2 rounded hover:bg-[#3a3f4b]/30 text-sm border border-[#3a3f4b]"
                >
                  <SeverityBadge severity={e.severity} compact />
                  <span className="flex-1 truncate text-gray-300">{e.title}</span>
                  <StatusBadge status={e.status} />
                </Link>
              ))}
              {ciEvents.length === 0 && (
                <p className="text-sm text-gray-500">Нет активных сигналов</p>
              )}
            </div>
            <Link to={`/console?ci=${selectedCi.id}`} className="text-xs text-[#4a9eff] hover:underline">
              Открыть в консоли →
            </Link>
          </div>
        )}
        {activeTab === 'params' && (
          <div className="bg-[#252830] border border-[#3a3f4b] rounded-lg p-4">
            <h3 className="text-sm font-medium text-white mb-3">Параметры КЕ</h3>
            <dl className="grid grid-cols-2 gap-3 text-sm">
              {[
                ['FQDN', selectedCi.fqdn],
                ['Тип', selectedCi.ciType],
                ['Система', selectedCi.system],
                ['Подсистема', selectedCi.subsystem],
                ['ПО', selectedCi.software],
                ['Тенант', product.tenant],
                ['Площадка', product.site],
              ].map(([k, v]) => (
                <div key={k}>
                  <dt className="text-xs text-gray-500">{k}</dt>
                  <dd className="text-gray-300 mt-0.5">{v}</dd>
                </div>
              ))}
            </dl>
            <div className="mt-4 flex flex-wrap gap-1">
              {[...selectedCi.tags, ...product.tags].map((tag) => (
                <span key={tag} className="px-2 py-0.5 text-xs rounded bg-[#3a3f4b]/50 text-gray-400">{tag}</span>
              ))}
            </div>
          </div>
        )}
        {activeTab === 'events' && (
          <div className="bg-[#252830] border border-[#3a3f4b] rounded-lg p-4">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-medium text-white">События КЕ</h3>
              <Link to={`/console?ci=${selectedCi.id}`} className="text-xs text-[#4a9eff] hover:underline">
                Консоль →
              </Link>
            </div>
            <div className="space-y-1">
              {events.filter((e) => e.ciId === selectedCi.id).slice(0, 10).map((e) => (
                <Link
                  key={e.id}
                  to={`/console/${e.id}`}
                  className="flex items-center gap-2 px-3 py-2 rounded hover:bg-[#3a3f4b]/30 text-sm"
                >
                  <StatusBadge status={e.status} />
                  <SeverityBadge severity={e.severity} compact />
                  <span className="flex-1 truncate text-gray-300">{e.title}</span>
                  <span className="text-xs text-gray-600">{e.createdAt.slice(0, 16)}</span>
                </Link>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

interface CiSidebarProps {
  product: ProductHealth;
  ciList: ConfigurationItem[];
  selectedCiId: string;
  onSelectCi: (ciId: string) => void;
}

export function CiSidebar({ product, ciList, selectedCiId, onSelectCi }: CiSidebarProps) {
  return (
    <div className="w-56 shrink-0 border-r border-[#3a3f4b] pr-4">
      <div className="text-xs text-gray-500 mb-2">{product.name}</div>
      <div className="space-y-1">
        {ciList.map((ci) => {
          const h = getCiHealth(ci.id);
          return (
            <button
              key={ci.id}
              type="button"
              onClick={() => onSelectCi(ci.id)}
              className={`w-full text-left px-2 py-2 rounded text-sm transition-colors ${
                selectedCiId === ci.id
                  ? 'bg-[#4a9eff]/15 border border-[#4a9eff]/40 text-white'
                  : 'hover:bg-[#3a3f4b]/30 text-gray-400 border border-transparent'
              }`}
            >
              <div className="font-mono text-xs truncate">{ci.fqdn}</div>
              <div className="mt-1">
                <HealthBadge level={h.currentHealth} compact percent={h.healthPercent} />
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );
}
